/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package popupframe;

import gui.JDBCConnection;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;

/**
 *
 * @author nguye
 */
public class DiemHocSinh_QuanLyLopPanel extends javax.swing.JFrame {

    /**
     * Creates new form DiemHocSinh_DanhSachLopPanel
     */
    String namhoc;
    String mshs;
    String tenlop;

    void loaddatabase() {
        DefaultTableModel model = (DefaultTableModel) this.hk1table.getModel();
        model.setRowCount(0);
        model = (DefaultTableModel) this.hk2table.getModel();
        model.setRowCount(0);
        String sqlkh1 = "EXEC sp_DanhSachLop_InDiemHocSinh " + namhoc + ",N'Học kì 1','" + mshs + "'";
        System.out.println(sqlkh1);
        String sqlkh2 = "EXEC sp_DanhSachLop_InDiemHocSinh " + namhoc + ",N'Học kì 2','" + mshs + "'";

        System.out.println(sqlkh2);

        try {
            Connection cn = JDBCConnection.ketNoiJBDC();
            CallableStatement cst = cn.prepareCall(sqlkh1);
            ResultSet r = cst.executeQuery();

            while (r.next()) {
                System.out.println("?????????????");
                String arr[] = {r.getString("TenMonHoc"), r.getString("Diem15Phut"), r.getString("Diem1Tiet"), r.getString("DiemTBM"), r.getString("DiemTBM")};
                addItemTableKH1(arr);
            }
        } catch (SQLException e) {
            System.out.println("unfound");
            return;
        }
        try {
            Connection cn = JDBCConnection.ketNoiJBDC();
            java.sql.CallableStatement cst = cn.prepareCall(sqlkh2);
            ResultSet r = cst.executeQuery();
            while (r.next()) {
                System.out.println("?????????????");
                String arr[] = {r.getString("TenMonHoc"), r.getString("Diem15Phut"), r.getString("Diem1Tiet"), r.getString("DiemTBM"), r.getString("DiemTBM")};
                addItemTableKH2(arr);
            }
        } catch (SQLException e) {

        }
    }

    void addItemTableKH1(String data[]) {
        DefaultTableModel tblM = (DefaultTableModel) this.hk1table.getModel();
        tblM.addRow(data);
    }

    void addItemTableKH2(String data[]) {
        DefaultTableModel tblM = (DefaultTableModel) this.hk2table.getModel();
        tblM.addRow(data);

    }

    public DiemHocSinh_QuanLyLopPanel(String lop, String nam, String ms) {
        initComponents();
        this.namhoc = nam;
        this.tenlop = lop;
        this.mshs = ms;
        this.clasLabel.setText(lop);
        this.yearLabel.setText(nam);
        this.IDLabel.setText(ms);
        loaddatabase();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        hk1table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        hk2table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        clasLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        hk1table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hk1table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Môn Học", "Điểm 15 phút", "Điểm 1 tiết", "Điểm trung bình"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hk1table.setFocusable(false);
        hk1table.setGridColor(new java.awt.Color(255, 255, 255));
        hk1table.setIntercellSpacing(new java.awt.Dimension(0, 1));
        hk1table.setSelectionBackground(new java.awt.Color(0, 176, 239));
        jScrollPane1.setViewportView(hk1table);
        if (hk1table.getColumnModel().getColumnCount() > 0) {
            hk1table.getColumnModel().getColumn(0).setResizable(false);
            hk1table.getColumnModel().getColumn(1).setResizable(false);
            hk1table.getColumnModel().getColumn(2).setResizable(false);
            hk1table.getColumnModel().getColumn(3).setResizable(false);
        }

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        hk2table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hk2table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Môn học", "Điểm 15 phút", "Điểm 1 tiết", "Điểm trung bình"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hk2table.setFocusable(false);
        hk2table.setGridColor(new java.awt.Color(255, 255, 255));
        hk2table.setIntercellSpacing(new java.awt.Dimension(0, 1));
        hk2table.setSelectionBackground(new java.awt.Color(0, 176, 239));
        jScrollPane2.setViewportView(hk2table);
        if (hk2table.getColumnModel().getColumnCount() > 0) {
            hk2table.getColumnModel().getColumn(0).setResizable(false);
            hk2table.getColumnModel().getColumn(1).setResizable(false);
            hk2table.getColumnModel().getColumn(2).setResizable(false);
            hk2table.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Mã số học sinh");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Lớp");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Năm Học");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Học kì 1");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Học kì 2");

        IDLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IDLabel.setText("name");

        yearLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        yearLabel.setText("year");

        clasLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clasLabel.setText("class");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(14, 14, 14)
                            .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(59, 59, 59)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(yearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addGap(33, 33, 33)
                            .addComponent(clasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(IDLabel)
                    .addComponent(yearLabel)
                    .addComponent(clasLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDLabel;
    private javax.swing.JLabel clasLabel;
    private javax.swing.JTable hk1table;
    private javax.swing.JTable hk2table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
