/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package popupframe;

import gui.JDBCConnection;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import thamso.LayThamSo;

/**
 *
 * @author Admin
 */
public class SuaHocSinh_QuanLiHocSinh extends javax.swing.JDialog {

    public static String getMaHocSinh = "";

    /**
     * Creates new form SuaHocSinh_QuanLiHocSinh
     */
    int NamSinhCuaTuoiToiThieu = Calendar.getInstance().get(Calendar.YEAR) - new LayThamSo().getTuoiToiThieu();
    int NamSinhCuaTuoiToiDa = Calendar.getInstance().get(Calendar.YEAR) - new LayThamSo().getTuoiToiDa();

    public SuaHocSinh_QuanLiHocSinh() {

        initComponents();
        datechooseHocSinh.getCalendarButton().setVisible(false);
        Date maxSelected = new GregorianCalendar(NamSinhCuaTuoiToiThieu, 11, 31).getTime();
        Date minSelected = new GregorianCalendar(NamSinhCuaTuoiToiDa, 0, 1).getTime();
        datechooseHocSinh.getDateEditor().setMaxSelectableDate(maxSelected);
        datechooseHocSinh.getDateEditor().setMinSelectableDate(minSelected);
        textChuThichTuoi.setText("Vui lòng nhập năm sinh giữa " + NamSinhCuaTuoiToiDa + " và " + NamSinhCuaTuoiToiThieu);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void capNhatHS() {

        int STT = -1;
        boolean KiemTra = true;
        if (!(txtEmailHocSinh.getText().contains("@") && txtEmailHocSinh.getText().contains("."))) {
            KiemTra = false;
            STT = 1;
        }
        Date checkYear = datechooseHocSinh.getDate();
        int year = checkYear.getYear() + 1900;
        if (year < NamSinhCuaTuoiToiDa || year > NamSinhCuaTuoiToiThieu) {
            KiemTra = false;
            STT = 2;
        }
        if (KiemTra == true) {
            int xacNhan = JOptionPane.showConfirmDialog(null, "Bạn có muốn lưu thông tin những dòng này", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (xacNhan == JOptionPane.YES_OPTION) {

                Connection con = JDBCConnection.ketNoiJBDC();

                //Tạo statement
                CallableStatement mystm;
                try {
                    mystm = con.prepareCall("{call sp_SuaHocSinh_SuaThongTin(?,?,?,?,?,?)}");
                    mystm.setString(1, getMaHocSinh);
                    mystm.setString(2, txtHoTenHocSinh.getText());
                    mystm.setString(3, new SimpleDateFormat("yyyy-MM-dd").format(datechooseHocSinh.getDate()));
                    if (rbNamHocSinh.isSelected()) {
                        mystm.setString(4, "Nam");
                    } else {
                        mystm.setString(4, "Nu");
                    }

                    mystm.setString(5, txtAreaDiaChiHocSinh.getText());
                    mystm.setString(6, txtEmailHocSinh.getText());

                    mystm.execute();
                    this.setVisible(false);
                } catch (SQLException ex) {
                    Logger.getLogger(SuaHocSinh_QuanLiHocSinh.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        } else {
            if (STT == 1) {
                JOptionPane.showMessageDialog(null, "Email bạn nhập đã sai!!");
            }
            if (STT == 2) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập năm sinh giữa 2003 và 2006!!");
            }

        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtHoTenHocSinh = new javax.swing.JTextField();
        String datePattern = "dd/MM/yyyy";
        String dateMask = "##/##/####";
        datechooseHocSinh = new com.toedter.calendar.JDateChooser(datePattern, dateMask, '_');
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtEmailHocSinh = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaDiaChiHocSinh = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rbNamHocSinh = new javax.swing.JRadioButton();
        rbNuHocSinh = new javax.swing.JRadioButton();
        CapNhatHocSinh = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        textChuThichTuoi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin học sinh"));

        jLabel10.setText("Họ tên:");

        datechooseHocSinh.setToolTipText("");
        datechooseHocSinh.setDateFormatString("dd/MM/yyyy");
        datechooseHocSinh.setMinimumSize(new java.awt.Dimension(200, 200));

        jLabel11.setText("Ngày sinh:");
        jLabel11.setAlignmentY(0.8F);

        jLabel12.setText("Email:");

        txtAreaDiaChiHocSinh.setColumns(12);
        txtAreaDiaChiHocSinh.setRows(5);
        txtAreaDiaChiHocSinh.setToolTipText(""); // NOI18N
        jScrollPane3.setViewportView(txtAreaDiaChiHocSinh);

        jLabel13.setText("Địa chỉ:");

        jLabel14.setText("Giới tính:");

        buttonGroup1.add(rbNamHocSinh);
        rbNamHocSinh.setText("Nam");

        buttonGroup1.add(rbNuHocSinh);
        rbNuHocSinh.setText("Nữ");

        CapNhatHocSinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/poly/app/icons/16x16/updated.png"))); // NOI18N
        CapNhatHocSinh.setText("Cập nhật");
        CapNhatHocSinh.setToolTipText("");
        CapNhatHocSinh.setAutoscrolls(true);

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/poly/app/icons/16x16/exit (1).png"))); // NOI18N
        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        textChuThichTuoi.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        textChuThichTuoi.setText("settext");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(CapNhatHocSinh)
                        .addGap(34, 34, 34)
                        .addComponent(Close))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(datechooseHocSinh, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                            .addComponent(txtHoTenHocSinh))
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)))
                                    .addComponent(textChuThichTuoi))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(rbNamHocSinh)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbNuHocSinh))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtEmailHocSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtHoTenHocSinh)
                    .addComponent(jLabel14)
                    .addComponent(rbNamHocSinh)
                    .addComponent(rbNuHocSinh))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmailHocSinh)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(datechooseHocSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textChuThichTuoi)
                                .addGap(11, 11, 11))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CapNhatHocSinh)
                    .addComponent(Close))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_CloseActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton CapNhatHocSinh;
    private javax.swing.JButton Close;
    private javax.swing.ButtonGroup buttonGroup1;
    public com.toedter.calendar.JDateChooser datechooseHocSinh;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JRadioButton rbNamHocSinh;
    public javax.swing.JRadioButton rbNuHocSinh;
    private javax.swing.JLabel textChuThichTuoi;
    public javax.swing.JTextArea txtAreaDiaChiHocSinh;
    public javax.swing.JTextField txtEmailHocSinh;
    public javax.swing.JTextField txtHoTenHocSinh;
    // End of variables declaration//GEN-END:variables
}
