/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package popupframe;

import gui.QuanLyLopPanel;
import gui.JDBCConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;

/**
 *
 * @author ADMIN
 */
public class ThemHocSinh_DanhSachHocSinhPanel extends javax.swing.JFrame {

    /**
     * Creates new form themhocsinhDialog
     */
    QuanLyLopPanel dsl;

//    boolean check(String mshs) {
//        String sql1 = "select * from HOCSINH where MaHocSinh= '" + mshs + "'";
//        String sql2 ="select * from QUATRINHHOC WHERE MaHocSinh='"+mshs+"'AND  MaLop is null";
//         System.out.println(sql2);
//        try {
//            Connection cn = JDBCConnection.ketNoiJBDC();
//            Statement sta = cn.createStatement();
//            ResultSet r = sta.executeQuery(sql1);
//
//            if (r.next()) {
//
//                this.warningLabel.setText("Hoc sinh:" + r.getString("HoTen"));
//                System.out.print("^^^^^^^^");
//            } else {
//                this.warningLabel.setText("Khong tim thay");
//                System.out.println("NO DATA");
//                return false;
//            }
//            r = sta.executeQuery(sql2);
//            if (!r.next()) {
//                System.out.println(sql2);
//                System.out.println("data  sql2 in themhocsinh_danhsachhocsinh");
//                 this.warningLabel.setText("Hoc sinh da co lop");
//                return false;
//
//            }
//        } catch (SQLException e) {
//            System.out.println("errror");
//        }
//        return true;
//
//    }

    public ThemHocSinh_DanhSachHocSinhPanel() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public ThemHocSinh_DanhSachHocSinhPanel(QuanLyLopPanel t) {
        initComponents();
        dsl = t;
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableHocSinh = new javax.swing.JTable();
        ThemMoi1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableHocSinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã học sinh", "Họ tên", "Ngày sinh", "Giới tính", "Địa chỉ", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableHocSinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableHocSinhMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableHocSinh);

        ThemMoi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/poly/app/icons/16x16/plus.png"))); // NOI18N
        ThemMoi1.setText("Thêm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(ThemMoi1)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(ThemMoi1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableHocSinhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHocSinhMousePressed
//        try {
//            DiemBanDau = tableHocSinh.getValueAt(tableHocSinh.getSelectedRow(), tableHocSinh.getSelectedColumn()).toString();
//        } catch (Exception e) {
//            DiemBanDau = "";
//        }
    }//GEN-LAST:event_tableHocSinhMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ThemMoi1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableHocSinh;
    // End of variables declaration//GEN-END:variables
}
