/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import thamso.LayThamSo;

/**
 *
 * @author Admin
 */
public class ManHinhDangNhap extends javax.swing.JDialog {

    /**
     * Creates new form ManHInhDangNhap
     */
    static ManHinhChinhFrame manHinhChinh;

    public ManHinhDangNhap(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        manHinhChinh.DangXuat.addMouseListener(new MouseListener() {

            public void mousePressed(MouseEvent e) {
                int xacNhan = JOptionPane.showConfirmDialog(null, "Đăng xuất", "Xác nhận", JOptionPane.YES_NO_OPTION);
                if (xacNhan == JOptionPane.YES_OPTION) {
                                        manHinhChinh.setVisible(false);
                    manHinhChinh.tblMainBoard.removeAll();
                    manHinhChinh.tblMainBoard.addTab("Dashboard", manHinhChinh.dashBoard);
                    manHinhChinh.tblMainBoard.addTab("Quản lý học sinh", manHinhChinh.quanLiHocSinh);
                    manHinhChinh.tblMainBoard.addTab("Quản lý lớp", manHinhChinh.quanLiLop);
                    manHinhChinh.tblMainBoard.addTab("Quản lý điểm số", manHinhChinh.quanLiDiemSo);

                    manHinhChinh.tblMainBoard.addTab("Tổng kết", manHinhChinh.tongKet);
                    manHinhChinh.tblMainBoard.addTab("Thay đổi quy định", manHinhChinh.thayDoiQuyDinh);

                    manHinhChinh.disableQLDiemSo.setEnabled(true);
                    manHinhChinh.disableTongKet.setEnabled(true);
                    manHinhChinh.disableTdQuyDinh.setEnabled(true);
                    manHinhChinh.disableQuanLyHS.setEnabled(true);

                    manHinhChinh.quanLiLop.addButton.setEnabled(true);
                    manHinhChinh.quanLiLop.ChuyenLopBtn.setEnabled(true);
                    manHinhChinh.quanLiLop.deleteButton.setEnabled(true);
                    manHinhChinh.quanLiLop.saveButton.setEnabled(true);
                    setVisible(true);
                }

            }

            public void mouseClicked(MouseEvent e) {

            }

            public void mouseReleased(MouseEvent e) {
            }

            public void mouseEntered(MouseEvent e) {
            }

            public void mouseExited(MouseEvent e) {
            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TenDangNhap = new javax.swing.JTextField();
        BtnDangNhap = new javax.swing.JButton();
        BtnThoat = new javax.swing.JButton();
        MatKhau = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tên Đăng Nhập:");

        jLabel2.setText("Mật Khẩu:");

        BtnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/poly/app/icons/16x16/graduated.png"))); // NOI18N
        BtnDangNhap.setText("Đăng nhập");
        BtnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDangNhapActionPerformed(evt);
            }
        });

        BtnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/poly/poly/app/icons/16x16/exit (1).png"))); // NOI18N
        BtnThoat.setText("Thoát");
        BtnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TenDangNhap)
                    .addComponent(MatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(BtnDangNhap)
                .addGap(18, 18, 18)
                .addComponent(BtnThoat)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDangNhap)
                    .addComponent(BtnThoat))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDangNhapActionPerformed

        Connection con = JDBCConnection.ketNoiJBDC();
        try {
            Statement stm = con.createStatement();

            String tenDangNhap = TenDangNhap.getText();
            String matKhau = MatKhau.getText();
            String sql = "select * from PhanQuyenDangNhap where TenDangNhap= '" + tenDangNhap + "' and MatKhau='" + matKhau + "'";
            ResultSet rs = stm.executeQuery(sql);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "Tên đăng nhập và mật khẩu không đúng");

            } else {

                String VaiTro = rs.getString("VaiTro");
                if (VaiTro.equals("quanli")) {

                    manHinhChinh.tblMainBoard.remove(3);
                    manHinhChinh.tblMainBoard.remove(3);
                    manHinhChinh.tblMainBoard.remove(3);

                    manHinhChinh.disableQLDiemSo.setEnabled(false);
                    manHinhChinh.disableTongKet.setEnabled(false);
                    manHinhChinh.disableTdQuyDinh.setEnabled(false);

                } else if (VaiTro.equals("giaovien")) {

                    manHinhChinh.tblMainBoard.remove(1);
                    manHinhChinh.tblMainBoard.remove(4);
                    manHinhChinh.disableQuanLyHS.setEnabled(false);
                    manHinhChinh.disableTdQuyDinh.setEnabled(false);
                    manHinhChinh.quanLiLop.addButton.setEnabled(false);
                    manHinhChinh.quanLiLop.ChuyenLopBtn.setEnabled(false);
                    manHinhChinh.quanLiLop.deleteButton.setEnabled(false);
                    manHinhChinh.quanLiLop.saveButton.setEnabled(false);
                }

                this.setVisible(false);

                manHinhChinh.setVisible(true);
            }

        } catch (SQLException ex) {
            Logger.getLogger(ManHinhDangNhap.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_BtnDangNhapActionPerformed

    private void BtnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LayThamSo().ketNoiCoSoDulieu();
                manHinhChinh = new ManHinhChinhFrame();
                ManHinhDangNhap dialog = new ManHinhDangNhap(new javax.swing.JFrame(), true);

                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDangNhap;
    private javax.swing.JButton BtnThoat;
    private javax.swing.JPasswordField MatKhau;
    private javax.swing.JTextField TenDangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
